id_joint:
  1  : ShoulderR
  2  : ShoulderL
  3  : ArmUpperR
  4  : ArmUpperL
  5  : ArmLowerR
  6  : ArmLowerL
  7  : PelvYR
  8  : PelvYL
  9  : PelvR
  10 : PelvL
  11 : LegUpperR
  12 : LegUpperL
  13 : LegLowerR
  14 : LegLowerL
  15 : AnkleR
  16 : AnkleL
  17 : FootR
  18 : FootL
  19 : Neck
  20 : Head
