id_joint:
  1  : ShoulderR
  2  : ShoulderL
  3  : ArmUpperR
  4  : ArmUpperL
  5  : ArmLowerR
  6  : ArmLowerL
  7  : PelvYR
  8  : PelvYL
  9  : PelvR
  10 : PelvL
  11 : LegUpperR
  12 : LegUpperL
  13 : LegLowerR
  14 : LegLowerL
  15 : AnkleR
  16 : AnkleL
  17 : FootR
  18 : FootL
  19 : Neck
  20 : Head
module_list: [none, head_control_module, base_module, walking_module, manipulation_module, action_module, walking_module, direct_control_module, online_walking_module]
module_button:
    1 : none
    2 : head_control_module
    3 : action_module
    4 : walking_module
    5 : online_walking_module
    6 : direct_control_module
